require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CounteroffersController do

  # This should return the minimal set of attributes required to create a valid
  # Counteroffer. As you add validations to Counteroffer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "offer" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CounteroffersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all counteroffers as @counteroffers" do
      counteroffer = Counteroffer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:counteroffers).should eq([counteroffer])
    end
  end

  describe "GET show" do
    it "assigns the requested counteroffer as @counteroffer" do
      counteroffer = Counteroffer.create! valid_attributes
      get :show, {:id => counteroffer.to_param}, valid_session
      assigns(:counteroffer).should eq(counteroffer)
    end
  end

  describe "GET new" do
    it "assigns a new counteroffer as @counteroffer" do
      get :new, {}, valid_session
      assigns(:counteroffer).should be_a_new(Counteroffer)
    end
  end

  describe "GET edit" do
    it "assigns the requested counteroffer as @counteroffer" do
      counteroffer = Counteroffer.create! valid_attributes
      get :edit, {:id => counteroffer.to_param}, valid_session
      assigns(:counteroffer).should eq(counteroffer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Counteroffer" do
        expect {
          post :create, {:counteroffer => valid_attributes}, valid_session
        }.to change(Counteroffer, :count).by(1)
      end

      it "assigns a newly created counteroffer as @counteroffer" do
        post :create, {:counteroffer => valid_attributes}, valid_session
        assigns(:counteroffer).should be_a(Counteroffer)
        assigns(:counteroffer).should be_persisted
      end

      it "redirects to the created counteroffer" do
        post :create, {:counteroffer => valid_attributes}, valid_session
        response.should redirect_to(Counteroffer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved counteroffer as @counteroffer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Counteroffer.any_instance.stub(:save).and_return(false)
        post :create, {:counteroffer => { "offer" => "invalid value" }}, valid_session
        assigns(:counteroffer).should be_a_new(Counteroffer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Counteroffer.any_instance.stub(:save).and_return(false)
        post :create, {:counteroffer => { "offer" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested counteroffer" do
        counteroffer = Counteroffer.create! valid_attributes
        # Assuming there are no other counteroffers in the database, this
        # specifies that the Counteroffer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Counteroffer.any_instance.should_receive(:update).with({ "offer" => "" })
        put :update, {:id => counteroffer.to_param, :counteroffer => { "offer" => "" }}, valid_session
      end

      it "assigns the requested counteroffer as @counteroffer" do
        counteroffer = Counteroffer.create! valid_attributes
        put :update, {:id => counteroffer.to_param, :counteroffer => valid_attributes}, valid_session
        assigns(:counteroffer).should eq(counteroffer)
      end

      it "redirects to the counteroffer" do
        counteroffer = Counteroffer.create! valid_attributes
        put :update, {:id => counteroffer.to_param, :counteroffer => valid_attributes}, valid_session
        response.should redirect_to(counteroffer)
      end
    end

    describe "with invalid params" do
      it "assigns the counteroffer as @counteroffer" do
        counteroffer = Counteroffer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Counteroffer.any_instance.stub(:save).and_return(false)
        put :update, {:id => counteroffer.to_param, :counteroffer => { "offer" => "invalid value" }}, valid_session
        assigns(:counteroffer).should eq(counteroffer)
      end

      it "re-renders the 'edit' template" do
        counteroffer = Counteroffer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Counteroffer.any_instance.stub(:save).and_return(false)
        put :update, {:id => counteroffer.to_param, :counteroffer => { "offer" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested counteroffer" do
      counteroffer = Counteroffer.create! valid_attributes
      expect {
        delete :destroy, {:id => counteroffer.to_param}, valid_session
      }.to change(Counteroffer, :count).by(-1)
    end

    it "redirects to the counteroffers list" do
      counteroffer = Counteroffer.create! valid_attributes
      delete :destroy, {:id => counteroffer.to_param}, valid_session
      response.should redirect_to(counteroffers_url)
    end
  end

end
